version: '3'

services:
    model:
        build: ./model
        ports:
            - "8501:8501"
        networks:
            - default

    backend:
        build: ./backend
        depends_on:
            - model
        ports:
            - "5000:5000"
        networks:
            - default

    frontend:
        build: ./frontend
        networks:
            - default

    proxy:
        build: ./proxy
        depends_on:
            - frontend
            - backend
        ports:
            - "80:80"
        networks:
            - default

networks:
    default:
        driver: bridge
